Add LST Distribution and Restakers trend chart (Operators Page)
NethermindEth/restaking-dashboard pull request #100
Opened 2024-06-28 19:40 UTC by Zishan-7

- Added LST distribution chart and integrated API
- Added Restakers trend chart and integrated API

Screenshot: 

<img width="626" alt="Screenshot 2024-06-29 at 1 09 50 AM" src="https://github.com/NethermindEth/restaking-dashboard/assets/72738005/697b42fc-d65d-40e6-985b-55022de865e0">

2024-07-01 09:27 UTC, vincenthongzy requested changes

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrend.jsx
> +  };
since you only used this once, it can be inside useEffect as an IIFE.

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrend.jsx
> +                  state.restakerTrend[state.restakerTrend.length - 1].restakers}
maybe return a N/A if its empty for some reason

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +  });
you are missing the dependency array for useCallback here

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +};
<img width="336" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/9f651490-a82b-4502-8939-e82cd8370abe">

tooltips shouldn't go out of bounds, it should reverse its direction

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +              textAnchor: 'end'
`nit`: we really should be using tailwind variables like font-xs and maybe define #7A86A5 in the tailwind config file.

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/OperatorDetails.jsx
> +          <RestakersTrend opAddress={address} />
<img width="629" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/b917ad3c-2562-4c43-8cf0-5f8163f8d292">

doesn't really look nice on mobile, let's grab the low hanging fruit and give it a row based layout on small screens

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +};
curious, why TooltipWithBounds here but TooltipWithPortal in the `OperatorTVLOverTime` component?

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +  const handleMouseMove = React.useCallback(
import at the top
```suggestion
  const handleMouseMove = useCallback(
```

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +      }
i don't think the logic here is working well, its kinda funky, i move it a little bit and its jumping between 3 points

https://github.com/NethermindEth/restaking-dashboard/assets/107991825/4bc6e228-5918-4535-a82a-6ab4dc0fe262

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +    fetchTVLOverTime();
are we calling it `Overtime` or `OverTime` ?

2024-07-01 09:27 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +            onMouseLeave={() => hideTooltip()}
```suggestion
            onMouseLeave={hideTooltip}
```

2024-07-01 09:29 UTC, vincenthongzy commented
priority to address the UI/UX , can leave the `nit` for later

2024-07-01 09:33 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
<img width="745" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/eb42e336-83c5-4822-a773-cb6c459d604f">

highly unlikely to have constant value over 7 days, but maybe can take some inspiration from https://github.com/NethermindEth/restaking-dashboard/pull/99#discussion_r1658112437 to create artificial ranges to make it look more natural

2024-07-01 10:04 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +    fetchTVLOverTime();
we are calling it `Overtime` in Kushagra's PR

2024-07-01 10:06 UTC, Zishan-7 commented on src/operators/RestakersTrendChart.jsx
> +};
Actually I used it to counter the same bug you mentioned. `TooltipWithBounds` is aware of its parent's boundaries and it flips if it is going out of bounds.

2024-07-01 10:09 UTC, Zishan-7 commented on src/operators/OperatorTVLOverTime.jsx
> +      }
This is a different chart component than that of Restakers Trend chart. We are aware of this tooltip bug and @kushagrasarathe is working to fix this. If the Restaker Trend chart looks okay to you then we can use that component instead of this one.

2024-07-01 10:22 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +};
It doesn't seem like its working 😅

2024-07-01 10:23 UTC, Zishan-7 commented on src/operators/RestakersTrendChart.jsx
> +};
Fixed it, working now

<img width="387" alt="Screenshot 2024-07-01 at 3 53 10 PM" src="https://github.com/NethermindEth/restaking-dashboard/assets/72738005/c02f702e-e2cf-456a-8669-9215e6be4837">

2024-07-01 10:24 UTC, vincenthongzy commented on src/operators/OperatorTVLOverTime.jsx
> +      }
@Zishan-7 can confirm the Restakers Trend chart is behaving as expected (apart from the out of bounds tooltip), but the actual tooltip behavior is sane.

2024-07-01 10:26 UTC, Zishan-7 commented on src/operators/OperatorTVLOverTime.jsx
> +      }
The tooltip bug is fixed. I will use that chart here as well

2024-07-01 11:29 UTC, Zishan-7 commented on src/operators/OperatorTVLOverTime.jsx
> +    fetchTVLOverTime();
Converted it to IIFE

2024-07-01 17:25 UTC, vincenthongzy commented on src/operators/RestakersTrendChart.jsx
> +      <svg width={width} height={height} className="overflow-visible">
hm what's with the overflow-visible changes here? do you have any screenshots?

2024-07-02 07:48 UTC, Zishan-7 commented on src/operators/RestakersTrendChart.jsx
> +      <svg width={width} height={height} className="overflow-visible">
The y-axis numbers get cut off without `overflow-visible`


<img width="180" alt="Screenshot 2024-07-02 at 1 15 42 PM" src="https://github.com/NethermindEth/restaking-dashboard/assets/72738005/d1565b9e-1054-4a2e-b0ee-4ad8672c67a6">


<img width="157"  alt="Screenshot 2024-07-02 at 1 15 55 PM" src="https://github.com/NethermindEth/restaking-dashboard/assets/72738005/45f1301d-fec1-414e-8d0c-f0aec8f9fa8e">

2024-07-02 09:26 UTC, vincenthongzy approved these changes

2024-07-02 14:39 UTC, merged