feat: overview page api integration
NethermindEth/restaking-dashboard pull request #101
Opened 2024-07-01 18:12 UTC by kushagrasarathe

added:
- top avs and operators api integration with loading states
- lrt distribution graphs api integration
- relevant services and methods 

todo:
- eigen tvl overtime api integration
- home page stats calculation and rendering

2024-07-02 14:11 UTC, vincenthongzy commented on src/home/EigenTvlOvertimeChart.jsx
> +const EigenTVLOvertimeChart = ({ data, width, height }) => {
ah nvm I think zishan is fixing this

2024-07-02 14:13 UTC, vincenthongzy commented on src/home/Home.jsx
> -import EigenTVLOvertime from './EigenTVLOvertime';
as per Ruben's comments, this should really be `EigenTVLOvertime`

2024-07-02 16:34 UTC, vincenthongzy requested changes

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
Did you go through the chart changes with Carlos? The tooltips feel abit laggy as well hm

what's implemented:
<img width="1197" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/e1532c5c-7383-44ff-969a-19f0918245f0">

mock:
<img width="813" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/bd4dbec5-34c8-4276-b811-981eb012e49c">

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
<img width="921" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/dd84a0da-5677-4fd2-a887-18ee48a97648">

on slighty smaller screens, the verbose dates are jumbled together

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
>        <div className="w-full flex flex-col gap-10 md:flex-row items-center justify-between px-4">
<img width="848" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/ac2f57d1-4b6a-4f80-a6c2-fabe8ba0119f">

the pie chart is cutoff on slightly smaller screens

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
>        <div className="w-full flex flex-col gap-10 md:flex-row items-center justify-between px-4">
had to go way smaller before the other layout kicked in

<img width="622" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/939681b9-2f43-4d3c-add9-d75a5440da05">

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertime.jsx
> +                <span>Eigen TVL over time</span>
```suggestion
                <span>EigenLayer TVL over time</span>
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertime.jsx
> +                <EigenTVLOvertimeChart
```suggestion
                <EigenLayerTVLOvertimeChart
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertime.jsx
> +                <span>Eigen TVL over time</span>
Eigen is the coin name, not the protocol name

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
> +    [dateScale, margin.left, showTooltip, getTvlByDate]
need to wrap getTvlByDate in useCallback, or move it into handleTooltip . Same for `getEthTVL` and `getLstTVL`
```suggestion
    [dateScale, margin.left, showTooltip]
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
> +            onMouseLeave={() => hideTooltip()}
`nit`

```suggestion
            onMouseLeave={hideTooltip}
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
> +            onMouseMove={handleTooltip}
hm why do we need so many events here?
```suggestion
            onTouchStart={handleTooltip}
            onTouchMove={handleTooltip}
            onMouseMove={handleTooltip}
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/EigenTVLOvertimeChart.jsx
seems like its laggy because of firing the event too many times and triggering alot of calculations for the tooltip

<img width="848" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/40de3dd8-f588-46ba-9af0-415943766a7a">

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/Home.jsx
> +  }, [avsService, operatorService, eigenService, dispatch]);
`nit`: these functions should be part of dependency array and wrapped with useCallback, or moved within. We only need specify the "child" dependencies like `dispatch` etc if the function body is moved inside

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
> +  }, [lrtService, dispatch]);
`nit`: The child dependencies are supposed to be specified in the `useCallback` instead. Or we move the function body in here and keep the same dep array
```suggestion
  }, [fetchLRTDistribution]);
```

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
> +  }, {});
think this should be wrapped in a useEffect and kept in state

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
> +  };
@Zishan-7 this is your `Other` LRT indexer right?

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
> +  const chartData = lrtPieChartData(lrtDataWithPercentages);
these should be useMemo'd, or calculated inside a useEffect and be part of state imo

2024-07-02 16:34 UTC, vincenthongzy commented on src/home/OverviewLRTDistribution.jsx
> +  const chartData = lrtPieChartData(lrtDataWithPercentages);
every state change on the active pie chart is causing these values to be calculated again and again

2024-07-03 10:06 UTC, kushagrasarathe commented on src/home/EigenTVLOvertimeChart.jsx
> +            onMouseMove={handleTooltip}
yes these are for touch screen devices

2024-07-03 10:38 UTC, kushagrasarathe commented on src/home/EigenTVLOvertimeChart.jsx
for the graph @Zishan-7  mentioned that the bar graph gets jumbled together for all tab data, which doesnt really look too good, he tried that on operators page, so after taking to Carlos, he suggested going with the line chart for now

2024-07-03 10:48 UTC, kushagrasarathe commented on src/home/EigenTVLOvertimeChart.jsx
@vincenthongzy I've added memos and callbacks for functions, but on the first load the tooltip still lags a little, but is smooth after first calculations are done, I'm pushing the changes, maybe you can have a look at it again later 🫡

2024-07-04 04:00 UTC, vincenthongzy approved these changes

2024-07-04 04:00 UTC, merged