AVS list page improvements
NethermindEth/restaking-dashboard pull request #117
Opened 2024-07-11 03:53 UTC by Zishan-7

- Updated the List to use NextUI table

2024-07-11 07:24 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +              }
might be worthwhile to have a look? https://nextui.org/docs/components/table#why-not-array-map

2024-07-11 07:30 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +              }
nvm took a look at the interface, seems like its really annoying to adapt to it

2024-07-15 04:06 UTC, vincenthongzy requested changes

2024-07-15 04:06 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +                      />
<img width="343" alt="image" src="https://github.com/user-attachments/assets/5155e19d-878f-4c6a-9e3b-c88ac99dfd96">

let's add `bg-foreground-2` to make some icons like Witness Chain and Brevis more visible

2024-07-16 07:41 UTC, vincenthongzy requested changes
text in table rows are not aligned , noticed that AVS name is not center aligned with the columns to its right

<img width="420" alt="image" src="https://github.com/user-attachments/assets/c24b2b3c-bb51-4b1b-89d8-2ab2a954abee">

2024-07-16 07:41 UTC, vincenthongzy commented on src/shared/Layout.jsx
> -        <div className="flex flex-col flex-1">
why was this necessary? does changing this break any other page's layout?

2024-07-16 07:41 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +    className: 'w-64 md:w-2/5'
OK i see that without this, on mobiles we get the table will all columns, then it expands into overflow and might not be a good UX. Will be good if you can also screenshot and comment so we can get better context on why these changes are necessary

2024-07-16 07:50 UTC, vincenthongzy requested changes
the search logic in the useEffect is a little buggy. Sometimes I search for non-existing address/names, it still shows me first page permanently or flash the first page then back to not found

https://github.com/user-attachments/assets/892bc647-d53b-4333-9178-4edf9a39bab2

2024-07-16 07:50 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +        <Table
please fix the warnings, missing `aria-label`

<img width="442" alt="image" src="https://github.com/user-attachments/assets/773af13e-c2df-49b2-b086-9ef5403bf0da">

2024-07-16 07:50 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +              <span className="text-foreground-active">No AVS found.</span>
should fix the pagination and disable everything

<img width="410" alt="image" src="https://github.com/user-attachments/assets/acf9f862-29f5-412f-876c-ff36e479efc0">

2024-07-16 07:50 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +                        <span class="material-symbols-outlined h-5 rounded-full text-lg text-yellow-300 min-w-5 flex justify-center items-center">
```suggestion
                        <span className="material-symbols-outlined h-5 rounded-full text-lg text-yellow-300 min-w-5 flex justify-center items-center">
```

2024-07-16 07:51 UTC, Zishan-7 commented on src/shared/Layout.jsx
> -        <div className="flex flex-col flex-1">
This prevents the content overflowing the screen on mobile devices. This change does not break other page layout but fixes it by preventing unnecessary horizontal overflow

with `flex-1`

![Screenshot 2024-07-16 at 1 18 10 PM](https://github.com/user-attachments/assets/5def23f7-c3fe-427c-b70e-29695f4c690b)

with `w-full`

![Screenshot 2024-07-16 at 1 19 07 PM](https://github.com/user-attachments/assets/f248aff4-08e4-417b-908e-9e7dbf728f08)

2024-07-16 10:43 UTC, Zishan-7 commented on src/avs/AVSList.jsx
> +              <span className="text-foreground-active">No AVS found.</span>
I have hidden the pagination component if table is empty

2024-07-16 10:47 UTC, Zishan-7 commented on src/avs/AVSList.jsx
> +    className: 'w-64 md:w-2/5'
We are using `layout= fixed` for the table. So to make the table scrollable in mobile devices we need to specify a fixed width instead of percentage so that the content overflows the table width and the scroll is enabled.
If we give the width in percentage the table will never scroll as it will try to fit into the available width

2024-07-16 10:52 UTC, Zishan-7 commented on src/@services/AVSService.js
> +
> the search logic in the useEffect is a little buggy. Sometimes I search for non-existing address/names, it still shows me first page permanently or flash the first page then back to not found. Please observe the behaviour when I search for `faj` multiple times
> 
>  Screen.Recording.2024-07-16.at.3.48.33.PM.mov

Added abort controller to counter the above mentioned bug. So if new search query is passed before the previous one was completed, it cancels the previous request and the results are only shown for the new one.

2024-07-16 10:55 UTC, Zishan-7 commented
> text in table rows are not aligned , noticed that AVS name is not center aligned with the columns to its right
> 
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/107991825/348987949-c24b2b3c-bb51-4b1b-89d8-2ab2a954abee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjc1ODcsIm5iZiI6MTcyMTEyNzI4NywicGF0aCI6Ii8xMDc5OTE4MjUvMzQ4OTg3OTQ5LWMyNGIyYjNjLWJiNTEtNGIxYi04OWQ4LTJhYjJhOTU0YWJlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMDU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTVhMDQyZmJlZGZlMTNiMDFhZjBlZjJkM2JlNGE4Nzk5ZGQ0Njc2MTkxYWRhODE5NGE5NTc4NGMxOWEyMmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lpsJAVA_A9-mk9qYQucGqTDyik5QKesWalUuDJxkvxk">

Fixed

2024-07-16 10:58 UTC, vincenthongzy commented on src/@services/AVSService.js
> +
the abort controller instantiation should be in the components useEffect

2024-07-16 12:07 UTC, Zishan-7 commented on src/@services/AVSService.js
> +
Got it. Fixing this

2024-07-16 20:02 UTC, rubo requested changes
Haven't yet reviewed the code closely, but there are a few things to address regarding the UI:

- The search input doesn't match the design. The border color.
- Pagination items are clickable `span` elements for some reason. Must be `Button` to show some interactivity.

2024-07-17 04:55 UTC, vincenthongzy commented on src/shared/Layout.jsx
> -        <div className="flex flex-col flex-1">
@rubo which pages are broken specifically, any screenshots? I've tested locally and it seems ok from my end. Most of the pages are currently broken on smaller screens, irregardless of this change

2024-07-17 07:34 UTC, Zishan-7 commented on src/avs/AVSList.jsx
> +    if (state.sortDescriptor) console.log(state.sortDescriptor); // capture user's selection and recall the API with sorting params
I have added it here as a dummy till we implement sorting.

2024-07-17 17:11 UTC, rubo requested changes
Also, I'd like to apply the following changes to our search:

- Start searching only when the input has 3 or more characters. Typing just "a" doesn't make sense.
- If it starts with "0x", search when it has 5 (maybe 4) or more characters as "0xa" doesn't make sense.

The above helps to reduce the number of requests to the server.
Also, I'd like to change the address search pattern to match from the beginning. It's very uncommon to search for an address by its end or by something in the middle.
CC @vincenthongzy

2024-07-17 17:11 UTC, rubo commented on src/shared/Pagination.jsx
> +      <button
I mean the Button component of NextUI. BTW, please take a look at [the Pagination samples](https://nextui.org/docs/components/pagination). It's pretty good out-of-the-box. Why do we have it customized?

2024-07-17 17:11 UTC, rubo commented on public/notFound.svg
We can drop this.

2024-07-17 17:11 UTC, rubo commented on src/avs/AVSList.jsx
> +          <Input
The search box styles need to be updated as per the design.

2024-07-18 03:07 UTC, vincenthongzy commented
> Also, I'd like to apply the following changes to our search:
> 
> * Start searching only when the input has 3 or more characters. Typing just "a" doesn't make sense.
> * If it starts with "0x", search when it has 5 (maybe 4) or more characters as "0xa" doesn't make sense.
> 
> The above helps to reduce the number of requests to the server. Also, I'd like to change the address search pattern to match from the beginning. It's very uncommon to search for an address by its end or by something in the middle. CC @vincenthongzy

1. Agree. We need to update the search bar with a placeholder like "Start searching [AVS/Operator] address/name with 3 or more characters" or have an "error" text above the input field when we detect there's less than 3 characters and no more keystroke is registered. 

2. Depends on how we want the experience to be like though, if I don't prefix `0x` does it mean I'm never searching for addresses?  Otherwise we need to match anywhere for addresses. However most likely people will just copy and paste an address instead of manually typing it in, so we might be fine with a more rigid logic and just treat query without `0x` as names only?

2024-07-18 14:11 UTC, Zishan-7 commented
> > Also, I'd like to apply the following changes to our search:
> > 
> > * Start searching only when the input has 3 or more characters. Typing just "a" doesn't make sense.
> > * If it starts with "0x", search when it has 5 (maybe 4) or more characters as "0xa" doesn't make sense.
> > 
> > The above helps to reduce the number of requests to the server. Also, I'd like to change the address search pattern to match from the beginning. It's very uncommon to search for an address by its end or by something in the middle. CC @vincenthongzy
> 
> 1. Agree. We need to update the search bar with a placeholder like "Start searching [AVS/Operator] address/name with 3 or more characters" or have an "error" text above the input field when we detect there's less than 3 characters and no more keystroke is registered so users don't get confused
> 2. Depends on how we want the experience to be like though, if I don't prefix `0x` does it mean I'm never searching for addresses?  Otherwise we need to match anywhere for addresses. However most likely people will just copy and paste an address instead of manually typing it in, so we might be fine with a more rigid logic and just treat query without `0x` as names only?

Should we add a tooltip next to search bar and mention our search criteria there?

2024-07-18 14:42 UTC, rubo commented
> Should we add a tooltip next to search bar and mention our search criteria there?

@Zishan-7 Yes, but you may skip it now to save time. Also, for now, we treat something as an address if it starts with "0x".

2024-07-18 19:22 UTC, rubo reviewed
The AVS list now looks good. No major issues. We just need to add sorting. There are a few things to think about:

- Given the NextUI's Pagination is pretty powerful and well thought, I think it doesn't make sense to have left/right arrows in the bottom corners. The component already provides those in different ways.
- The hover color for the table header is gray -- we need to change it. If it's not straightforward, we can leave it for later, as there are some hover issues in NextUI.

2024-07-19 06:28 UTC, Zishan-7 commented
> The AVS list now looks good. No major issues. We just need to add sorting. There are a few things to think about:
> 
> * Given the NextUI's Pagination is pretty powerful and well thought, I think it doesn't make sense to have left/right arrows in the bottom corners. The component already provides those in different ways.
> * The hover color for the table header is gray -- we need to change it. If it's not straightforward, we can leave it for later, as there are some hover issues in NextUI.

- I have changed the header hover color
- I will create a separate PR for adding sorting.

2024-07-19 07:01 UTC, vincenthongzy requested changes
@rubo fix the linters other errors in a separate PR? Some of them can be fixed by deleting some unused files entirely after #118 is merged

2024-07-19 07:01 UTC, vincenthongzy commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
Hm I don't like how the `useDebounce` signature now includes a very specific parameter that's only applicable for search bars.

We should keep this hook simple, and handle the validation at the table's useEffect hook before calling the API. So something like?:

```
if(validateSearchTerm) {
    avsService.getAll(...)
}
```

2024-07-19 07:41 UTC, vincenthongzy commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
with this logic, we will need to update backend behaviour? So backend doesn't do an `$or` match anymore, but check if the query starts with `0x` then we match with `address` field, otherwise match `metadata.name` only?

```
// fe
  const validateSearchTerm = query => {
    const minQueryLength = query.startsWith('0x') ? 5 : 3;
    return query.length === 0 || query.length > minQueryLength;
  };

// be
           // update this so no need for `or` anymore?
            {
              $or: [
                { 'metadata.name': { $regex: new RegExp(search, 'i') } },
                { address: { $regex: new RegExp(search, 'i') } }
              ]
            }
```

2024-07-19 07:48 UTC, Zishan-7 commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
> with this logic, we will need to update backend behaviour? So backend doesn't do an $or match anymore, but check if the query starts with 0x then we match with address field, otherwise match metadata.name only?
Thanks for pointing this I will update the logic.

2024-07-19 07:51 UTC, Zishan-7 commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
> Hm I don't like how the useDebounce signature now includes a very specific parameter that's only applicable for search bars.

I added this directly in `useDebounce` to avoid writing the same `validateSearchTerm` logic in the components where search is needed assuming the criteria for search will be same across all other components.

2024-07-19 08:02 UTC, vincenthongzy commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
The `useDebounce` hook should still be generic, so I would prefer moving it up and live with minimal duplication, or rename it to a more specific `useDebouncedSearch`

2024-07-19 08:27 UTC, vincenthongzy requested changes

2024-07-19 08:27 UTC, vincenthongzy commented on tailwind.config.js
> +    },
this shouldn't be inside tailwind config, because the height is specific for some pages only.

2024-07-19 08:32 UTC, vincenthongzy commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
@Zishan-7 does it run on your end?
<img width="593" alt="image" src="https://github.com/user-attachments/assets/21435115-5936-4aae-afd8-ae90f3209cad">

2024-07-19 10:20 UTC, Zishan-7 commented on src/shared/hooks/useDebounce.jsx
> +const useDebounce = (value, delay, isSearchTerm) => {
Renamed the hook to `useDebouncedSearch`

2024-07-19 10:20 UTC, Zishan-7 commented on tailwind.config.js
> +    },
Got it, fixed.

2024-07-22 01:52 UTC, vincenthongzy approved these changes
We don't support a combination of sorting for now yeah? I.e desc stakers + asc TVL

2024-07-22 01:57 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +    false
don't this false is necessary
```suggestion
```

2024-07-22 02:02 UTC, vincenthongzy commented on src/shared/hooks/useDebouncedSearch.jsx
> +    return query.length === 0 || query.length > minQueryLength;
```suggestion
    return query.length === 0 || query.length >= minQueryLength;
```

2024-07-22 03:03 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +              <span className="material-symbols-outlined text-subtitle">
deprecating usage of `-subtitle`
```suggestion
              <span className="material-symbols-outlined text-foreground-2">
```

2024-07-22 05:36 UTC, Zishan-7 commented
> We don't support a combination of sorting for now yeah? I.e desc stakers + asc TVL

No its just singe sorting field right now

2024-07-22 12:24 UTC, rubo approved these changes

2024-07-22 15:33 UTC, merged