Refactor AVSDetails layout implementation
NethermindEth/restaking-dashboard pull request #118
Opened 2024-07-11 12:53 UTC by vincenthongzy

2024-07-11 12:54 UTC, vincenthongzy commented on src/avs/helpers.js
should probably move them to a global helper, splitting them into LST/LRT/beacon/EIGEN mappings

2024-07-11 13:50 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +          {avs.metadata?.name ?? 'N/A'}
The AVS name font doesn't match the design one. See the title style in the AVS list view.

2024-07-11 14:47 UTC, rubo requested changes

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +      <div className="my-4 text-sm text-foreground-1 break-words">
Also, let's add the rank placeholder not forget later. I mean the box next to the name like `#8`.

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +          className="text-sm text-secondary"
All these texts should be small according to the design: `text-xs`.

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
Good usage of controls. Well done. BTW, let's add Twitter handle as well: `X @handle`

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetails.jsx
> +                Total ETH value
The font size doesn't match the design. Should be `text-sm`. Also, let's change "Total ETH value" to just "Total value" as we already have ETH below and bring ETH before the amount like "ETH 1,000,000".

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +                  <div className="text-sm text-subtitle">
The font size doesn't match the design. Should be `text-xs`. Also, please use `text-foreground-2` instead of `text-subtitle`.

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +  const handleCopy = useCallback(value => {
This copy confirmation is cool. I think we can extract it to a separate component like `<Copy value={...} />` to use in operators and maybe stakers.

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +function TwitterIcon() {
I see we need X icon not only in footer now. So we need it as a separate asset. I'll make one.

2024-07-11 14:47 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +function CopyIcon() {
Not sure why we use SVG here. Google Font icons should be used instead. For this particular one,

```html
<span className="material-symbols-outlined">content_copy</span>
```

2024-07-12 06:52 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
@rubo it looks kinda strange

<img width="382" alt="image" src="https://github.com/user-attachments/assets/f1ddb57b-4f15-40f1-8785-3c0701f4d835">

2024-07-12 07:02 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +        <AVSLogo avs={avs} />
we could do a `background-color: white` as a temp measure
<img width="599" alt="image" src="https://github.com/user-attachments/assets/fad72ed3-2c73-422c-9f0d-02f220a0acfd">

2024-07-12 07:08 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +                Total ETH value
ETH to the front will be fixed once formatters are merged in

2024-07-12 08:17 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +        <AVSLogo avs={avs} />
<img width="596" alt="image" src="https://github.com/user-attachments/assets/bb01eccb-e402-43b3-a966-8c510c485147">

2024-07-12 13:02 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +        <AVSLogo avs={avs} />
The problem with white is that it hides the white logos :) I discussed this with Carlos previously, so you may try another color like `foreground-2`. There's no silver bullet for this.

2024-07-12 13:04 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
That could be because the X logo is too large. Can you slightly shrink it?

2024-07-12 13:12 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +        <AVSLogo avs={avs} />
good call, Omni Network has a white logo. Updated

2024-07-12 13:36 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
still looks abit werid
<img width="859" alt="image" src="https://github.com/user-attachments/assets/d661758c-8d1f-4c8e-a8fa-5702b8797ff6">

2024-07-12 14:28 UTC, rubo requested changes

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +          </Button>
Shorter way:

```suggestion
          <Button
            variant="ghost"
            isIconOnly
            className="border-none ml-1 text-secondary"
            size="sm"
            onClick={() => handleCopy(avs.address)}
          >
            <span className="material-symbols-outlined">
              {state.isCopied ? 'check' : 'content_copy'}
            </span>
          </Button>
```

Let's not alter icon styles so they are the same across the app. But I do agree that bolder checkmark looks better :)

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +            target="blank"
That function seems redundant:

```suggestion
            href={`https://etherscan.io/address/${avs.address}`}
            target="_blank"
```

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +
```suggestion
```

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +        )}
Slightly shorter way with a Twitter handle and smaller icon:

```suggestion
        {!!avs.metadata?.twitter && (
          <Button
            variant="ghost"
            as={Link}
            href={avs.metadata.twitter}
            target="_blank"
            rel="noreferrer"
            size="sm"
            className="ml-12 border-none text-secondary"
          >
            <span
              className="bg-secondary h-4 w-4"
              style={{ mask: 'url(/assets/x.svg) no-repeat' }}
            ></span>
            @
            {avs.metadata.twitter.substring(
              avs.metadata.twitter.lastIndexOf('/') + 1
            )}
          </Button>
        )}
```

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +}
```suggestion
```

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +                    {formatNumber(total, compact)} tokens
"tokens" is redundant. If it's easy, we can show the respective token symbol. If not, you can just skip it.

```suggestion
                    {formatNumber(total, compact)}
```

2024-07-12 14:28 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +          onPress={() => setIsOpen(!isOpen)}
Although `onPress` works, it throws an error in console:
> Warning: Unknown event handler property `onPress`. It will be ignored.

The modern approach is:

```suggestion
          onPointerDown={() => setIsOpen(!isOpen)}
```

2024-07-12 14:51 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
Not that bad ;) What is weird to me is the gap between the X and the copy button.

![image](https://github.com/user-attachments/assets/fa909f68-d57a-4274-8ade-d4a1c4b1e63b)

2024-07-16 08:23 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +        )}
Updated it with backgroud-color, otherwise the icon is not visible on the dark background

2024-07-16 08:25 UTC, vincenthongzy commented on src/avs/AVSDetailsTVLTab.jsx
> +                    {formatNumber(total, compact)} tokens
updated
<img width="587" alt="image" src="https://github.com/user-attachments/assets/1d30983c-6777-4422-8d6c-75ef18ba3c54">

2024-07-16 08:29 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +            as={Link}
fixed

2024-07-16 11:53 UTC, rubo requested changes
This PR is very close to being done. Good job!

Please pay attention to linter warnings.

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetails.jsx
> +import { formatETH, formatNumber } from '../shared/formatters';
Fix import order to silence the linter:

```suggestion
import { BEACON_STRATEGY, EIGEN_STRATEGY } from './helpers';
import { formatETH, formatNumber } from '../shared/formatters';
import { Skeleton, Tab, Tabs } from '@nextui-org/react';
import AVSDetailsHeader from './AVSDetailsHeader';
import AVSDetailsOperatorsTab from './AVSDetailsOperatorsTab';
import AVSDetailsTVLTab from './AVSDetailsTVLTab';
import { reduceState } from '../shared/helpers';
import { useEffect } from 'react';
import { useMutativeReducer } from 'use-mutative';
import { useParams } from 'react-router-dom';
import { useServices } from '../@services/ServiceContext';
import { useTailwindBreakpoint } from '../shared/useTailwindBreakpoint';
```

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetails.jsx
> +  }, []);
You forgot the dependencies:

```suggestion
  }, [address, avsService, dispatch]);
```

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetails.jsx
> +    (async () => {
To display error messages and hide loading indicators, we must wrap server calls with `try/catch/finally` everywhere. It's better to do this in a separate PR. What do you think?

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
Let's sort props and class names everywhere alphabetically until we apply the plugin.

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +import { Link, Image, Button, Skeleton } from '@nextui-org/react';
Please address formatting and import ordering warnings

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsHeader.jsx
> +function AVSLogo({ avs }) {
Do we really need this as a separate component with skeleton? `Image` should have a built-in one.

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +import {
Please address linter warnings

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +      <div className="bg-content1 border border-outline flex items-center justify-center h-[512px] p-4 rounded-lg w-full">
I'd rather add bottom margin here for a gap:

```suggestion
      <div className="bg-content1 border border-outline flex items-center justify-center h-[512px] mb-4 p-4 rounded-lg w-full">
```

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +        <div className="basis-1/2 mt-4 md:ml-4">
...and remove `mt` from here. Also, instead of `<Spacer/>,` it's better to use a flexbox and remove margins for the treemap.

```suggestion
      <div className="flex flex-col md:flex-row gap-4 w-full h-full">
        <div className="basis-1/2 flex flex-col gap-4">
          <TokensBreakdownList
            totalTokens={totalTokens}
            isAVSLoading={isAVSLoading}
            ethRate={ethRate}
          />
          <LSTBreakdownList
            lst={lst}
            isAVSLoading={isAVSLoading}
            ethRate={ethRate}
          />
        </div>
        {/* treemap */}
        <div className="basis-1/2">

```

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +          [...new Array(12)].map((_, i) => (
Same as above for destructuring :)

2024-07-16 11:53 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +          [...new Array(3)].map((_, i) => (
Doesn't this work just the same? :)

```suggestion
          new Array(3).map((_, i) => (
```

2024-07-16 11:53 UTC, rubo commented on src/avs/helpers.js
> +export const STRATEGY_ASSET_MAPPING = {
Please sort exports alphabetically.

2024-07-17 04:40 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
Add `'react/jsx-sort-props': 'warn'` to `eslint.config.js` so this is autofixable?

2024-07-17 04:51 UTC, vincenthongzy commented on src/avs/helpers.js
> +export const STRATEGY_ASSET_MAPPING = {
It's a little too much mental overhead to think of sorting stuff manually. I did a quick search and there is not much eslint tooling available that supports sorting exports except for https://www.npmjs.com/package/eslint-plugin-sort-exports

2024-07-17 04:52 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
And tailwind classes, I don't think its worth the effort to sort them manually for now. Let's just automatically fix them once you have evaluated the prettier plugin.

2024-07-17 05:52 UTC, vincenthongzy commented on src/avs/helpers.js
> +export const STRATEGY_ASSET_MAPPING = {
fixed, but moving forward seems inefficient to manually sort things.

2024-07-17 05:58 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
How far should we go with sorting?


<img width="499" alt="image" src="https://github.com/user-attachments/assets/efe8492e-0c8c-4da9-b562-2ed947505dca">

I would argue `width height src` is more readable then `height src width`

2024-07-17 05:59 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +function AVSLogo({ avs }) {
Placeholder because I did not want to spend the time searching for a good enough placeholder icon to use with `Image`'s `fallbackPathSrc`

2024-07-17 05:59 UTC, vincenthongzy commented on src/avs/AVSDetailsHeader.jsx
> +function AVSLogo({ avs }) {
can change it to an actual `.svg` if you'd like

2024-07-17 06:04 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +    (async () => {
Created an issue, let's do this in a new PR

2024-07-17 06:14 UTC, vincenthongzy commented on src/avs/AVSDetailsTVLTab.jsx
> +      <div className="bg-content1 border border-outline flex items-center justify-center h-[512px] p-4 rounded-lg w-full">
I will fix this in #123 to prevent breaking the graphs

2024-07-17 08:12 UTC, rubo commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
Not far. If you don't wanna fix existing ones, skip them but do that for new ones you add. For your specific example above, I agree that width and height together is way better than alphabetically ordered. However, you can't find that kinda good logic for hundreds of css classes, so it's just easier to have them all sorted alphabetically than think how to group them. It's like Prettier. You may not like its formatting but it's consistent and you don't think about it.

2024-07-17 08:27 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +            isAVSLoading={state.isAVSLoading}
OK I'll keep that in mind. I've fixed everything except for the tailwind classes. I will fix them in #123 because there are some new classes there and I'd like to avoid too much conflicts

2024-07-17 10:29 UTC, vincenthongzy commented on src/avs/AVSDetailsTVLTab.jsx
> +                    {formatNumber(total, compact)} {tokens[key].symbol}
I noticed that the symbol should be in front, fixed in #123 together with the EIGEN prefix

2024-07-18 20:16 UTC, rubo commented on src/avs/AVSDetails.jsx
> +          panel: 'p-0'
This fixes the tabs styling: no such class as `h-100`, replaced with `h-fit`; added `cursor` slot to match the design and fixed the tab corner radius which is wrong on the design. Some of those slots we can make shared to use for similar tabs elsewhere.

```suggestion
        className="my-4 w-full"
        classNames={{
          cursor: 'border border-outline shadow-none rounded',
          panel: 'p-0',
          tab: 'h-fit p-2',
          tabList: 'bg-content1 border border-outline p-2 rounded-lg w-full'
```
Design vs actual:
![ba](https://github.com/user-attachments/assets/a63dfc14-c437-4d37-a70b-43120c058db4)

2024-07-19 06:37 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +          panel: 'p-0'
good eye

2024-07-19 16:51 UTC, rubo approved these changes

2024-07-19 16:54 UTC, rubo commented
Please comment out the AVS rank next to the title.

2024-07-24 14:10 UTC, merged