Add charts for AVS details page tabs
NethermindEth/restaking-dashboard pull request #123
Opened 2024-07-16 09:53 UTC by vincenthongzy

2024-07-16 16:55 UTC, rubo requested changes
Please apply formatting to files. I'll add it to workflows as well.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +                      className="fill-[#465e99]"
Please put a comment here to replace the hardcoded color later.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +                  `${formatNumber(tooltipData.value, compact)} EIGEN`
Currency symbol should come first to match our formatting:

```suggestion
                  `EIGEN ${formatNumber(tooltipData.value, compact)}`
```

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +import { scaleUtc, scaleLinear } from '@visx/scale';
Apply formatting.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +const bisectDate = bisector(getDate).left;
Please move this to the bottom.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +  }, [points]);
`dispatch` should be in the dependencies list.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +  }, [points, state.useRate]);
`compact` must be in the dependency list.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +    [scaleDate, scaleValue, state.filteredPoints]
`getValue` and `showTooltip` must be in the dependency list.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +              {growthPercentage > 0 && '+'}
Why don't we display `-` for negative growth?

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +        <div className="flex flex-1 w-full flex-col gap-y-2 justify-between sm:flex-row sm:justify-end gap-x-2">
The breakpoint (and any other prefixes) should be ignored when sorting. Hence, `flex-col sm:flex-row` should be together as they do the same thing. I'm wondering what formatting plugin will do in this case.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +          />
Let's remove grid columns. Too many lines.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +            className="stroke-dark-blue"
Please put comment here to replace the hardcoded color. Also, let's make the line smoother.
```suggestion
            className="stroke-dark-blue"
            curve={curveMonotoneX}
```

Don't forget to import `curveMonotoneX`.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +            <g>
`<g>` looks redundant.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +          <AxisRight
The fonts on both axes are incorrect. See the LRT chart.

2024-07-16 16:55 UTC, rubo commented on src/avs/AVSDetailsTVLTab.jsx
> +              height={512}
The chart height is too large. 288 looks way better.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +            tickFormat={v => formatNumber(v, true)}
The `formatNumber` must be the one from `formatters.js`. This one must be removed.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +export default function OperatorsTabLineChart({ points, height, width }) {
Please apply all the requested changes to this chart as well.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +  }, [points]);
`dispatch` should be in the dependencies list.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +  }, [points, state.useRate]);
`state.useRate` should not be a dependency here.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +  }, [state.filteredPoints, state.useRate]);
`state.useRate` should not be a dependency here.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +    [scaleDate, scaleValue, state.filteredPoints]
`getValue` and `showTooltip` should be in the dependency list.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/OperatorsTabLineChart.jsx
> +              {formatNumber(growthPercentage, false)}%
`formatNumber` must be the one from `formatters.js`.

2024-07-16 16:55 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +              {formatNumber(growthPercentage, false)}%
The `formatNumber` must be the one from formatters.js.

2024-07-17 06:25 UTC, vincenthongzy commented on src/avs/charts/TVLTabTreemap.jsx
> +const ALL_STRATEGY_ASSET_MAPPING = { ...LST_STRATEGY_ASSET_MAPPING, [EIGEN_STRATEGY]: { name: 'Eigen', symbol: 'EIGEN' }, [BEACON_STRATEGY]: { name: 'Beacon', symbol: 'ETH' } }
Are you talking about renaming `LST_STRATEGY_ASSET_MAPPING` the constant , or `ALL_STRATEGY_ASSET_MAPPING` which is a derived mapping from the constant or both?

2024-07-17 06:27 UTC, vincenthongzy commented on src/avs/charts/TVLTabTreemap.jsx
> +      tooltipTop: point.y
What extensions in your IDE are you using to get type check errors? I don't think vanilla javascript tooling warns about type mismatches since that's only reserver for typescript tooling

2024-07-17 06:29 UTC, vincenthongzy commented on src/avs/charts/TVLTabTreemap.jsx
> +                      className="fill-[#465e99]"
this is one off and not used anywhere else, don't think its necessary to put this in tailwind config ?

2024-07-17 10:08 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +        <div className="flex flex-1 w-full flex-col gap-y-2 justify-between sm:flex-row sm:justify-end gap-x-2">
The tailwind team is pretty opinionated about this https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted. It's not in alphabetical order

2024-07-17 10:33 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +              {growthPercentage > 0 && '+'}
Because the percentage returned by the function returns actual signed integers directly. We only need to add in a '+' for consistency with the design

2024-07-17 10:38 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +            className="stroke-dark-blue"
wdym by hardcoded colour? It should be a prop or a tailwind variable?

2024-07-17 10:39 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +          />
without grid columns
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/4bd9d5a0-03f0-4d0c-9d38-135b12fc7476">

2024-07-17 10:39 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +          />
without any lines
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/1f255e8e-1235-4018-b9b3-0d65eb98f351">

2024-07-17 10:41 UTC, vincenthongzy commented on src/avs/charts/TVLTabLineChart.jsx
> +          />
Think it looks slighty weird with just the rows. IMO having the whole grid or no grid at all looks much nicer

2024-07-17 14:06 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +            className="stroke-dark-blue"
The class name already says it's blue. Although we can have a green color under the name "blue", it's weird and confusing. There should be a color-invariant name, like we have for fonts -- "foreground-2".

2024-07-17 14:12 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +const ALL_STRATEGY_ASSET_MAPPING = { ...LST_STRATEGY_ASSET_MAPPING, [EIGEN_STRATEGY]: { name: 'Eigen', symbol: 'EIGEN' }, [BEACON_STRATEGY]: { name: 'Beacon', symbol: 'ETH' } }
Both.

2024-07-17 14:13 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +      tooltipTop: point.y
This is a minor thing. VSCode warned that.

2024-07-17 14:17 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +                      className="fill-[#465e99]"
Generally, every color should be configurable. While this looks good for the current dark mode, the designer may choose another color for the light mode. There are a few places where I used "-black" and "-white" class names, given they stay the same for the light mode as well, but they may need to be moved to config.

2024-07-17 14:18 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +        <div className="flex flex-1 w-full flex-col gap-y-2 justify-between sm:flex-row sm:justify-end gap-x-2">
I'll take a look. Thanks.

2024-07-17 14:35 UTC, rubo commented on src/avs/charts/TVLTabLineChart.jsx
> +          />
We have horizontal lines on LRT chart as well. The ordinate axis is more important here as it shows the value, so lines are good to have. I used a bit darker color for lines on LRT chart, so they are not that visible as here but I think here they look better. The logic behind this is, first, to make it more valuable for users (by showing some lines) and only then think about how nice it is. But I don't have strong opinions here.

2024-07-19 06:10 UTC, merged