Refactor and add preliminary error handling
NethermindEth/restaking-dashboard pull request #129
Opened 2024-07-21 17:58 UTC by rubo

Added basic error handling and refactored as follows:

- Created `BaseService` class that all service classes must inherit. Currently, only `LRTService` derives from it to avoid conflicts with other PRs.
- `BaseService` provides error parsing and essential API call functions instead of `apiCall`
- Implemented error handling in LRT view
- Extracted TVL data loading to its dedicated control
- Introduced preliminary ErrorMessage component to customize later when needed
- Small style adjustments for error messages

This is what LRT TVL errors look like:

![Screenshot 2024-07-21 193544](https://github.com/user-attachments/assets/19e376ee-22fa-415e-a520-1282f79c44bb)

2024-07-22 11:31 UTC, Zishan-7 requested changes

2024-07-22 11:31 UTC, Zishan-7 commented on src/@services/BaseService.js
> +      method: options?.method?.toUpperCase() || 'get'
```suggestion
      method: options?.method?.toUpperCase() || 'get',
      signal: options?.signal
```

We need it for adding `abortController` to handle multiple search queries fired by the user at the same time

2024-07-22 12:04 UTC, Zishan-7 approved these changes

2024-07-23 02:38 UTC, vincenthongzy approved these changes

2024-07-23 10:08 UTC, rubo commented on src/lrt/LRTTotalValue.jsx
> +            )}
Yeah, I agree. We can do so with later PRs.

2024-07-23 10:08 UTC, merged