Add AVS operators table
NethermindEth/restaking-dashboard pull request #130
Opened 2024-07-22 09:46 UTC by vincenthongzy

2024-07-22 15:57 UTC, rubo requested changes
The Share column title and items are misaligned. I know the design also looks like that, but let's fix it and left align.

![image](https://github.com/user-attachments/assets/46033bc3-92d7-47cd-98f8-8ffe6569e112)

2024-07-23 03:01 UTC, vincenthongzy commented on src/@services/apiCall.js
> +    signal: options?.signal
rebased accordingly

2024-07-23 03:02 UTC, vincenthongzy commented on src/@services/AVSService.js
> +      throw new Error(await response.json());
will update after you merge #129

2024-07-23 03:04 UTC, vincenthongzy commented on src/avs/AVSDetailsOperatorsTab.jsx
> +          placeholder="Search by address/name with 3 characters or more..."
updated to have same phrasing as AVS List

2024-07-23 03:29 UTC, vincenthongzy commented
> The Share column title and items are misaligned. I know the design also looks like that, but let's fix it and left align.
> 
> ![image](https://private-user-images.githubusercontent.com/337518/351031302-46033bc3-92d7-47cd-98f8-8ffe6569e112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDU2MzUsIm5iZiI6MTcyMTcwNTMzNSwicGF0aCI6Ii8zMzc1MTgvMzUxMDMxMzAyLTQ2MDMzYmMzLTkyZDctNDdjZC05OGY4LThmZmU2NTY5ZTExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMzI4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTIxZjg3ZmViZmZkNjRkYTZkZWMwMTQ2Mzg5NWE0ZTIyOWQxZGRjYjgxYTc4YTZkMmE4ZDM5MTY4ODg3YTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UhyLSoIREZGrmN3R-SbCVIC0Wus3XviHzTVu-KgITug)

centered instead

2024-07-23 10:26 UTC, rubo commented
I have mixed feelings about this center alignment, but okay, let's leave it as is.

![image](https://github.com/user-attachments/assets/8ef538d7-c454-48e4-a968-ead42c75a04e)

2024-07-24 03:49 UTC, vincenthongzy commented
> I have mixed feelings about this center alignment, but okay, let's leave it as is.
> 
> ![image](https://private-user-images.githubusercontent.com/337518/351288058-8ef538d7-c454-48e4-a968-ead42c75a04e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTMyNDksIm5iZiI6MTcyMTc5Mjk0OSwicGF0aCI6Ii8zMzc1MTgvMzUxMjg4MDU4LThlZjUzOGQ3LWM0NTQtNDhlNC1hOTY4LWVhZDQyYzc1YTA0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwMzQ5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVlYzY5ODU5MWRlNDAxNzU1OGFmMWNkZGMwZWYzZjAxYzQ4OGMxZjAwNjY4YmM5MzNjOTg0N2U3NjU2ODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BAQ0wv6IbBxnLapYIjF__HBCGSI_wqFKF2DRYOsMa7c)

I made it the same as AVS List, left-aligned

2024-07-24 07:12 UTC, Zishan-7 approved these changes
LGTM

2024-07-24 14:06 UTC, rubo approved these changes

2024-07-24 14:06 UTC, rubo commented on src/avs/AVSDetailsOperatorsTab.jsx
> +        className="overflow-x-scroll"
This is redundant and shows a scrollbar always. Removing.

```suggestion
```

2024-07-24 14:07 UTC, merged