Add error handling (AVS list)
NethermindEth/restaking-dashboard pull request #133
Opened 2024-07-23 15:01 UTC by Zishan-7

- Added default sorting indication
- Added error handling
- Modified table empty state

This is how the errors will look:

<img width="1512" alt="Screenshot 2024-07-23 at 8 26 33 PM" src="https://github.com/user-attachments/assets/3f6e8ffa-2097-4ae4-965f-5f7d0219429a">

When there is no AVS found for a search query the table headers will not be shown

<img width="1512" alt="Screenshot 2024-07-23 at 8 28 42 PM" src="https://github.com/user-attachments/assets/b6d5eef9-2eaa-4fa5-ba1b-f78e17260698">

2024-07-23 19:50 UTC, rubo requested changes
It shows the second screen with "No result found..." instead of an error. We need an error message regardless of whether it's a search or not.

The default sorting shows up fine.

2024-07-23 19:50 UTC, rubo commented on src/avs/AVSList.jsx
> +              table: 'h-full'
Not related to this PR, but I noticed a weird thing and couldn't find an "official" way to get rid of it. Changed the colors, so you can spot it:

![image](https://github.com/user-attachments/assets/12302887-8ea4-4536-b910-9ac7675c8d8c)

This empty space is on each table. @vincenthongzy, you need to apply this to your tables as well.

```suggestion
              table: 'h-full',
              thead: '[&>tr:last-child]:hidden'
```

2024-07-24 09:47 UTC, Zishan-7 commented on src/avs/AVSList.jsx
> +              table: 'h-full'
Added suggested change to the table component.

2024-07-24 13:06 UTC, rubo commented on src/avs/AVSList.jsx
>              isFetchingAvsData: false
Minor. Please follow the naming convention -- `isFetchingAVSData.` As this view loads only AVS data, we can keep it short `isFetching` or `isFetchingData`...

2024-07-24 13:42 UTC, rubo requested changes
We made a mistake here. Please see https://github.com/NethermindEth/restaking-dashboard-backend/pull/95.

So, if there's an error, we display an error message using the `ErrorMessage` component as you have on the first screen. But, if AVS is not found, it returns an empty collection, and you show the second screen.

2024-07-24 15:57 UTC, rubo approved these changes

2024-07-24 15:57 UTC, merged