Refactor operator list
NethermindEth/restaking-dashboard pull request #142
Opened 2024-07-25 16:06 UTC by Zishan-7

- Added sort filter
- Refactored Operator list to match with AVS list implementation.

2024-07-25 18:13 UTC, rubo requested changes
- When no operator is found, it shows that as an error while it should not.
 - Paddings of list items are different from AVS ones.

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
Please rename the file to `OperatorList.jsx`

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +    if (debouncedSearchTerm) params.search = debouncedSearchTerm;
Let's avoid using single-line `if` statements _everywhere_. They're not readable and, in some cases, seem to cover the line below while it doesn't.

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +        <div className="text-foreground-1 lg:w-2/3">
The font size is too big for this text. We need `text-xs` here.

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +          placeholder="Search by Operator"
No need to make "operator" capitalized. I even thinking about "Search by name/address".

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +    label: 'Operators',
Must either be "Operator" or "Name".

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +                    No Operators found for &quot;
```suggestion
                    No operator found for &quot;
```

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
> +
Please remove redundant whitespaces.

2024-07-25 18:13 UTC, rubo commented on src/operators/OperatorsList.jsx
Please group variable declarations and put a space after them, not between them.

2024-07-25 18:23 UTC, rubo requested changes

2024-07-25 18:23 UTC, rubo commented on src/operators/OperatorsList.jsx
>  const OperatorsList = () => {
```suggestion
export default function OperatorList() {
```

2024-07-25 18:23 UTC, rubo commented on src/operators/OperatorsList.jsx
>  export default OperatorsList;
```suggestion
```

2024-07-26 09:24 UTC, Zishan-7 commented on src/operators/OperatorsList.jsx
> +          placeholder="Search by Operator"
"Search by name/address" makes more sense. Should I update it?

2024-07-26 09:35 UTC, Zishan-7 commented on src/operators/OperatorsList.jsx
> +    label: 'Operators',
I changed it to"Operator" to align with the AVS table

2024-07-26 12:38 UTC, rubo commented on src/operators/OperatorsList.jsx
> +          placeholder="Search by Operator"
Yes, please.

2024-07-26 12:56 UTC, rubo commented on src/operators/OperatorsList.jsx
> +        <div className="text-foreground-1 lg:w-2/3">
I disagree but let's keep it to compare to LRT which has that text smaller.

2024-07-26 13:19 UTC, rubo approved these changes

2024-07-26 13:27 UTC, merged