Refactor Top AVS, Operators and stats
NethermindEth/restaking-dashboard pull request #157
Opened 2024-07-30 12:27 UTC by Zishan-7

2024-07-30 12:29 UTC, Zishan-7 commented on src/home/Home.jsx
> +
Added this here to save multiple API calls. We can pass this data to Eigenlayer TVL chart component through props.

2024-07-30 17:11 UTC, rubo requested changes

2024-07-30 17:11 UTC, rubo commented on src/home/OverviewStats.jsx
> +        <div className="h-fusll flex min-h-10 basis-1/3 flex-col items-center gap-2 border-x border-outline px-2">
`h-fusll` not needed even without typo :)

2024-07-30 17:11 UTC, rubo commented on src/home/OverviewStats.jsx
> +        <div className="flex basis-1/3 flex-col items-center gap-1">
The gap here is 1 while for "Total AVS" is 2.

2024-07-30 17:13 UTC, rubo commented on src/home/Home.jsx
> +
Good but please change `Eigenlayer` to `EigenLayer`.

2024-07-30 19:05 UTC, Zishan-7 commented on src/home/OverviewStats.jsx
> +        <div className="h-fusll flex min-h-10 basis-1/3 flex-col items-center gap-2 border-x border-outline px-2">
Oops! left it there by mistake.

2024-07-30 19:39 UTC, rubo commented on src/home/OverviewStats.jsx
> +        <div className="h-fusll flex min-h-10 basis-1/3 flex-col items-center gap-2 border-x border-outline px-2">
Well, turned out it wasn't a mistake. We need `h-full justify-center` on all of them not to have too short border:

![image](https://github.com/user-attachments/assets/ce77d136-89c1-4f56-aea0-e2de524c62ba)

2024-07-30 19:40 UTC, rubo requested changes
Let's fix paddings for skeletons and we're good for now.

![Screenshot 2024-07-30 212946](https://github.com/user-attachments/assets/f72fb92e-f5b7-4cb5-b936-1b05d663469a)

2024-07-30 19:42 UTC, rubo requested changes

2024-07-30 19:42 UTC, rubo commented on src/home/OverviewStats.jsx
> +          <span className="text-center text-xs text-foreground-1 md:text-sm">
`text-center` looks redundant

2024-07-30 19:42 UTC, rubo commented on src/home/OverviewStats.jsx
> +            <span className="text-center">
This `span` looks redundant.

2024-07-30 20:06 UTC, rubo requested changes

2024-07-30 20:06 UTC, rubo commented on src/home/OverviewStats.jsx
> +      className: 'w-64 md:w-2/5 ps-12'
```suggestion
      className: 'w-64 md:w-2/5 ps-4'
```

2024-07-30 20:06 UTC, rubo commented on src/home/OverviewStats.jsx
> +      className: 'w-64 md:w-2/5 ps-12'
```suggestion
      className: 'w-64 md:w-2/5 ps-4'
```

2024-07-31 08:10 UTC, Zishan-7 commented on src/home/OverviewStats.jsx
> +        <div className="h-fusll flex min-h-10 basis-1/3 flex-col items-center gap-2 border-x border-outline px-2">
According to the designs it has short borders 🤔

<img width="604" alt="Screenshot 2024-07-31 at 1 38 34 PM" src="https://github.com/user-attachments/assets/7592b70f-2221-433a-aa95-c8588737c026">

2024-07-31 08:47 UTC, rubo approved these changes

2024-07-31 08:47 UTC, merged