Refactor LST page
NethermindEth/restaking-dashboard pull request #162
Opened 2024-08-02 01:51 UTC by vincenthongzy

2024-08-02 01:56 UTC, vincenthongzy commented on tailwind.config.js
> +              12: '#4fc3f7'
added 1 more shade of yellow `ffcc80` and 1 more shade of blue `4fc3f7`

2024-08-02 01:56 UTC, vincenthongzy commented on src/lst/LSTList.jsx
> +      <Table
Different from LRT, opted to use Table here because easier to get the correct widths for the columns

2024-08-02 01:56 UTC, vincenthongzy commented on src/lst/LSTDistributionGraph.jsx
> +            {state.keys.map((key, i) => {
@rubo I noticed that in LRT page you sort based on `tooltipData` but this seems to have slight issues with the color legends.

In the LRTList below , `Swell` could be yellow color. But in the tooltip depending on the data point, `Swell` could be any of the viable chart colors depending on the sorting order on that day

2024-08-02 02:13 UTC, vincenthongzy commented on tailwind.config.js
> +              12: '#4fc3f7'
oopd looks like I broke the color of the line charts

2024-08-02 02:18 UTC, vincenthongzy commented on tailwind.config.js
> +              12: '#4fc3f7'
fixed

2024-08-02 11:33 UTC, Zishan-7 commented
The graph behaves a bit weirdly for me: 

- On page load, graph shows all the data but the brush shows 3 months timeline

<img width="1287" alt="Screenshot 2024-08-02 at 5 00 00 PM" src="https://github.com/user-attachments/assets/7787b64c-70af-4c95-8bd3-7ba13e6eef15">

- If i move the brush to the left side it overflows and shows up over the actual graph
<img width="1279" alt="Screenshot 2024-08-02 at 5 00 35 PM" src="https://github.com/user-attachments/assets/0746f6d2-7fd9-4689-96c3-069c9d18c97e">

2024-08-02 12:12 UTC, Zishan-7 requested changes

2024-08-02 12:12 UTC, Zishan-7 commented on src/lst/LSTDistributionGraph.jsx
> +      filterPoints: points.slice(-90),
```suggestion
      filteredPoints: points.slice(-90),
```
This will fix the brush and graph timeline mismatch on page load as well

2024-08-02 18:18 UTC, rubo requested changes
- Tooltip title padding is missing
- The pointer indicator vertical line is misplaced
- The brush colors are wrong

![image](https://github.com/user-attachments/assets/6f646ccb-ab80-4d3c-8c6a-e10fa93461f4)

This PR definitely isn't ready for a review. Making it draft. Please mark it as ready when the obvious issues are addressed.

2024-08-02 18:18 UTC, rubo commented on src/lst/LST.jsx
>          Liquid Staking Tokens
Capitalization must be like everywhere else:

```suggestion
        Liquid staking tokens
```

2024-08-02 18:18 UTC, rubo commented on src/lst/LSTList.jsx
> +                    <span
We need to show here the logos as it was previously and as we have it on the design. I'll commit the updated LST logos to this branch later.

2024-08-05 03:01 UTC, vincenthongzy commented on src/lst/LSTDistributionGraph.jsx
> +            {state.keys.map((key, i) => {
I was looking at an old implement in LRTDistribution when I should have looked at LRTList instead, hence the confusion.

2024-08-05 03:05 UTC, vincenthongzy commented on src/lst/LSTDistributionGraph.jsx
> +            {state.keys.map((key, i) => {
Anyways the problem is we shouldn't sort the day's data in the graph because it will cause the color legends to be incorrect. Notice Eigenpie and Kelp colors are swapped. This is because the whole graph is sorted by the latest day's data 

```
      keys: Object.entries(data?.[data.length - 1].protocols)
        .sort(sortProtocols)
        .map(([k]) => k)
```

But in LRT's tooltip we are sorting by each day's data again, causing the color legends to be incosistent with the overall graph.


<img width="252" alt="image" src="https://github.com/user-attachments/assets/1a16552d-bca8-4fa4-a3e1-b805a7f3cb75">


<img width="246" alt="image" src="https://github.com/user-attachments/assets/ff496912-f8f2-4df0-9b3c-9449b3fe20b7">

2024-08-05 07:30 UTC, Zishan-7 approved these changes

2024-08-05 15:39 UTC, rubo requested changes

2024-08-05 15:39 UTC, rubo commented on tailwind.config.js
> +              12: '#4fc3f7'
We just need 2 extra colors here. No need to modify already existing ones as it badly affects other parts of UI.

2024-08-05 15:40 UTC, rubo approved these changes
Colors revised.

2024-08-05 15:41 UTC, merged

2024-08-05 19:32 UTC, rubo commented on src/lst/LSTDistributionGraph.jsx
> +            {state.keys.map((key, i) => {
This is a very good catch! Fixed in https://github.com/NethermindEth/restaking-dashboard/pull/163/commits/8eab7bbce1e868382af3345f58a888ff4515da30 so the tooltip is always sorted and doesn't display anything not on the graph for a given point unlike LST. Thus, LST chart needs to be changed that way. However, both approaches don't handle the case where protocol may be in the past but not in the present.