Adjust all graphs to default to 'All' timeline
NethermindEth/restaking-dashboard pull request #177
Opened 2024-08-14 06:01 UTC by vincenthongzy

2024-08-14 06:56 UTC, Zishan-7 approved these changes

2024-08-14 09:42 UTC, rubo requested changes
- Refactored LRT/LST approach to have a single point of control. Using `ParentSize` is problematic as it fires lots of negative values.
- All other changes have no effect as setting the default selected key doesn't fire the handler. AVS TVL is a fixed sample suggestion.

2024-08-14 09:46 UTC, rubo commented
I'm not sure changing the default time range is a good idea at all. The more time passes, the less sense it makes.

2024-08-23 09:11 UTC, vincenthongzy commented on src/avs/charts/OperatorsTabLineChart.jsx
> +const margin = { top: 20, right: 40, bottom: 30, left: 20 };
bumped the margins for line charts, otherwise the leftmost date label on 1w graphs gets gobbled up

2024-08-23 09:25 UTC, vincenthongzy commented on src/avs/charts/OperatorsTabLineChart.jsx
> +const margin = { top: 20, right: 40, bottom: 30, left: 20 };
<img width="340" alt="image" src="https://github.com/user-attachments/assets/669db909-e382-49b7-902e-468c35ea1c99">

Notice `Aug` also gets cut off

2024-08-23 10:14 UTC, Zishan-7 approved these changes

2024-08-23 14:53 UTC, rubo commented on src/operators/charts/OperatorRestakersLineChart.jsx
> +const margin = { top: 20, right: 40, bottom: 30, left: 20 };
```suggestion
const margin = { top: 20, right: 40, bottom: 30, left: 0 };
```

2024-08-23 14:53 UTC, rubo commented on src/operators/charts/OperatorTVLLineChart.jsx
> +const margin = { top: 20, right: 40, bottom: 30, left: 20 };
```suggestion
const margin = { top: 20, right: 40, bottom: 30, left: 0 };
```

2024-08-23 14:56 UTC, merged