Fix AVS details minor bugs
NethermindEth/restaking-dashboard pull request #179
Opened 2024-08-14 13:58 UTC by vincenthongzy

2024-08-14 14:16 UTC, vincenthongzy commented
There is another issue, https://www.notion.so/nethermind/Total-operators-count-doesn-t-match-list-numbering-287b83b103084af8b201fcc19a0fb460?pvs=4. I think this is not really fixable, it's probably due to the gap between avs indexer and operator indexer?

2024-08-14 14:26 UTC, rubo requested changes
The "No distribution message" must not be an error message. It's not an error. Better to copy the "not found" message styling from AVS list.

2024-08-20 08:18 UTC, Zishan-7 approved these changes

2024-08-20 12:50 UTC, rubo commented on src/avs/charts/TVLTabTreemap.jsx
> +    () => root.children.reduce((acc, child) => acc + child.data.value, 0) === 0,
It throws here for AVS `0x18343aa10e3d2f3a861e5649627324aead987adf`:

> TypeError: Cannot read properties of undefined (reading 'reduce')

2024-08-21 09:08 UTC, vincenthongzy commented on src/avs/charts/TVLTabTreemap.jsx
> +    () => root.children.reduce((acc, child) => acc + child.data.value, 0) === 0,
I am not able to reproduce locally when running on staging DB, but I've added in a guard to prevent this from happening

2024-08-22 13:13 UTC, rubo approved these changes

2024-08-22 13:13 UTC, rubo commented on src/avs/AVSDetailsOperatorsTab.jsx
> +                        : `${((op.strategiesTotal / tvl) * 100).toFixed(2)} %`}
```suggestion
                        : `${((op.strategiesTotal / tvl) * 100).toFixed(2)}%`}
```

2024-08-22 13:14 UTC, merged