Add promoted operators
NethermindEth/restaking-dashboard pull request #203
Opened 2024-08-30 12:09 UTC by vincenthongzy

2024-09-03 07:08 UTC, Zishan-7 requested changes
On `/operators` page when search result is empty, the promoted operators rows expand to take all of the available space

Also ETH -> USD conversion shows `NaN` when search result is empty. This happens on the AVS details page as well

<img width="1282" alt="Screenshot 2024-09-03 at 12 34 39 PM" src="https://github.com/user-attachments/assets/922d68a6-d3a5-4383-b1b3-dad30946d96e">

2024-09-03 07:10 UTC, vincenthongzy commented
> On `/operators` page when search result is empty, the promoted operators rows expand to take all of the available space
> 
> Also ETH -> USD conversion shows `NaN` when search result is empty. This happens on the AVS details page as well
> 
> <img alt="Screenshot 2024-09-03 at 12 34 39 PM" width="1282" src="https://private-user-images.githubusercontent.com/72738005/363874705-922d68a6-d3a5-4383-b1b3-dad30946d96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDc2NjMsIm5iZiI6MTcyNTM0NzM2MywicGF0aCI6Ii83MjczODAwNS8zNjM4NzQ3MDUtOTIyZDY4YTYtZDNhNS00MzgzLWIxYjMtZGFkMzA5NDZkOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjNkN2Y0NjFhNjg2MmJkZWQ1ZmMwNDJhZWNhNzhiNmUxNzI0NzI2ZDY3ZDJhMDkxY2RkYWQyY2NmNjNlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vJvQrEfM0DuTuNhWvqNCqcmTGNmAkkoaJeKXpPUA-Hk">

Hm strange, the expanding rows on empty results should have been fixed

2024-09-03 09:03 UTC, vincenthongzy commented
> On `/operators` page when search result is empty, the promoted operators rows expand to take all of the available space
> 
> Also ETH -> USD conversion shows `NaN` when search result is empty. This happens on the AVS details page as well
> 
> <img alt="Screenshot 2024-09-03 at 12 34 39 PM" width="1282" src="https://private-user-images.githubusercontent.com/72738005/363874705-922d68a6-d3a5-4383-b1b3-dad30946d96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTA3NjcsIm5iZiI6MTcyNTM1MDQ2NywicGF0aCI6Ii83MjczODAwNS8zNjM4NzQ3MDUtOTIyZDY4YTYtZDNhNS00MzgzLWIxYjMtZGFkMzA5NDZkOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA4MDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ODgzM2QzZWE2ZDg1NmJhMmFmOTBjYWQ0Nzg0MzM5NmVkOWI1NmM5M2UwYWMwNmRiMDQ2ZTM2NzBhOGY1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aK9CB3Pn7WTwiXK4qS03myB5_EXzdfsM5fc92brjj8">

Fixed by decoupling the promoted operators' rate and normal operators' rate on both BE and FE

2024-09-03 13:51 UTC, rubo commented on src/avs/AVSDetailsOperatorsTab.jsx
> +        //TODO: handle error
Why no error handling?

2024-09-04 02:41 UTC, vincenthongzy commented on src/avs/AVSDetailsOperatorsTab.jsx
> +        //TODO: handle error
If the promoted operators endpoint fails, we don't need to display error, so we just swallow it up

2024-09-04 14:16 UTC, Zishan-7 approved these changes

2024-09-04 16:05 UTC, rubo commented on src/avs/AVSDetailsOperatorsTab.jsx
> +        //TODO: handle error
That `TODO` confused me.

2024-09-04 16:05 UTC, rubo approved these changes

2024-09-04 16:06 UTC, vincenthongzy commented on src/avs/AVSDetailsOperatorsTab.jsx
> +        //TODO: handle error
I'll reword this comment

2024-09-05 04:18 UTC, merged