Spice ai migration
NethermindEth/restaking-dashboard pull request #55
Opened 2023-09-12 17:20 UTC by rachit2501

- AWS Serverless function for spice ai queries
- Deposit and withdraw on you replaced with the above endpoints
- NOT TO MERGE UNTIL ETH BEACON DATA PR IS MERGED

2023-10-03 13:41 UTC, Hyodar requested changes

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +        '0xae78736cd615f374d3085123a210448e74fc6393'
Similarly in other queries and in the `TokenSeries` CTEs.

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +  const stEth: DailyTokenData[] = [];
`stEthDeposits` seems better, similarly in other places.

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +  const array = response.toArray();
`deposits` seems better.

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +  const rEthWithdrawls: any[] = [];
`any` should also almost always be avoided.

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +export const getWithdrawals = async (
Most of the comments in `getDeposits` and `getStrategyDepositLeaderBoard` also apply here.

2023-10-03 13:41 UTC, Hyodar commented on api/package.json
> +  "description": "This template demonstrates how to make a simple HTTP API with Node.js and Typescript running on AWS Lambda and API Gateway using the Serverless Framework v3",
Boilerplate

2023-10-03 13:41 UTC, Hyodar commented on api/spice.ts
> +const spiceClient = new SpiceClient(process.env.SPICE || "");
Where is this env variable defined? Add an `.env.example` file with the expected keys (without the values of course).

2023-10-03 13:41 UTC, Hyodar commented on api/spice.ts
> +const spiceClient = new SpiceClient(process.env.SPICE || "");
Also, `SPICE_API_KEY` seems a lot better than `SPICE`.

2023-10-03 13:41 UTC, Hyodar commented on api/yarn.lock
Why is there both `package-lock.json` and `yarn.lock`? This is not right, you should either be using npm or yarn and the locks can conflict.

2023-10-03 13:41 UTC, Hyodar commented on api/handler.ts
> +    body: JSON.stringify([stEthDeposits, cbEthDeposits, rEthDeposits]),
Why returning an array? Similarly in all other routes.
Returning an object in this case is a lot better, so you know what's what (e.g. `{ stEthDeposits, cbEthDeposits, rEthDeposits }`).

2023-10-03 13:41 UTC, Hyodar commented on app/utils.ts
> +    `${process.env.NEXT_PUBLIC_SERVERLESS_URL}/deposits`
This env variable key should be added to `.env.example`. Also, something like `NEXT_PUBLIC_SPICE_PROXY_API_URL` seems better for me, but feel free to think more about it.

2023-10-03 13:41 UTC, Hyodar commented on app/utils.ts
> +export async function getDashboardData() {
The requests here are not being done in client-side, but this can be done in another PR.

2023-10-03 13:41 UTC, Hyodar commented on app/utils.ts
> +export async function getDashboardData() {
When this is done, however, remember to do all the requests async. You don't need to use `Promise.all()` for that unless you want to await all of them. You can, e.g.:
```ts
async function someAsyncFunction(): Promise<number> { return 0; }
async function someOtherAsyncFunction(): Promise<number> { return 1; }

async function main() {
  const a = someAsyncFunction(); // a is a promise
  const b = someOtherAsyncFunction(); // b is also a promise
  
  const c = await a + 1;
  const d = c + await b + await a; // no problem double awaiting a
}
```

2023-10-03 13:41 UTC, Hyodar commented on app/utils.ts
> +  console.log(stakersStEth);
Debugging log.

2023-10-03 13:41 UTC, Hyodar commented on package.json
> +    "dev": "next dev -p 3001",
?

2023-10-03 13:41 UTC, Hyodar commented on lib/spiceAi.ts
Doesnt't make sense to have this here anymore.

2023-10-03 13:42 UTC, Hyodar commented on api/handler.ts
Where are the cumulative queries?

2023-10-03 13:46 UTC, Hyodar requested changes

2023-10-03 13:46 UTC, Hyodar commented on app/utils.ts
> +  );
We'd previously talked about this. This should not be done client-side unless there's a really good reason for that, and the way you did is actually a server-side build, so it doesn't make sense at all. Also, from my tests here, adding the cumulative values as columns the deposits and withdrawals queries themselves (it's just a sum over with partition) didn't change the query time at all.

2023-10-04 19:14 UTC, rachit2501 commented on package.json
> +    "dev": "next dev -p 3001",
This was required since the api server was using port 3000

2023-10-11 01:52 UTC, Hyodar requested changes
Not an exhaustive review, just what I could check today. Some more suggestions, lmk wyt.

2023-10-11 01:52 UTC, Hyodar commented on api/handler.ts
I think this query will not work for the cumulative values, please check the query in our discord conversation.

2023-10-11 01:52 UTC, Hyodar commented on api/handler.ts
> +  // @ts-ignore
Would be better to quickly type this, it's not a hard type.

2023-10-11 01:52 UTC, Hyodar commented on api/handler.ts
> +export async function dailyBeaconChainETHDeposit() {
This should not be needed with the functions above. We could also make the validator queries separately if there's some gain in perf, but let's keep it simple on this PR.

2023-10-11 01:52 UTC, Hyodar commented on api/package.json
Typos: Strip, stripe. Actually, there are these typos all over the place.

2023-10-11 01:52 UTC, Hyodar commented on example.env
Not sure I got these changes. Supabase url and key shouldn't be public (neither does the api url for now, it's only needed for exposing it to the client). Also, stripe typo.

2023-10-11 01:52 UTC, Hyodar commented on lib/utils.ts
> +  total_shares: number | null;
Is everything nullable? Maybe those `| null` can be dropped.

2023-10-11 01:52 UTC, Hyodar commented on lib/utils.ts
> +export interface Withdraws {
Withdraws, withdrawls -> withdrawals. Multiple cases of this in other files I guess.

2023-10-11 01:52 UTC, Hyodar commented on api/handler.ts
> +      default:
This shouldn't be a default IMO, this is a case null. Default would mean any other token address maps to a beacon chain deposit.

2023-10-11 01:52 UTC, Hyodar commented on api/handler.ts
> +      await SpiceClient.query(`SELECT SUM(effective_balance)/POW(10,9) as final_balance
`SpiceClient` should probably be `spiceClient`. Multiple cases of this.

2023-10-11 16:19 UTC, rachit2501 commented on api/handler.ts
> +      default:
the query only tackles 4 cases right? so default will always be null based on that.

2023-10-12 08:59 UTC, Hyodar commented on api/handler.ts
> +      default:
Yes, and no. You 'can' think it's like that, but there's no notable benefit from doing this and it can lead to issues - e.g. a new token would be put in the beacon data basket.
A default is usually implemented as a fallback, not as an else, and in this case even an else would not be nice.

2023-11-21 21:23 UTC, Hyodar approved these changes

2023-11-21 21:23 UTC, merged