Timeline selection
NethermindEth/restaking-dashboard pull request #61
Opened 2023-11-15 15:16 UTC by tdenisenko

- Timeline selection and grouping for charts
- Some refactoring

2023-11-23 05:45 UTC, Hyodar requested changes
Hey, good work! Some small points, though nothing too major.

2023-11-23 05:45 UTC, Hyodar commented on api/package-lock.json
Hey, please use `yarn` on this - having both `yarn.lock` and `package-lock.json` can lead to some dep issues.

2023-11-23 05:45 UTC, Hyodar commented on api/serverless.yml
> +    timeout: 40
Usually API Gateway's integration has a hard limit on 30 seconds, so I don't think it makes sense that we increase it to 40s, which should work only locally. Has anything changed and API Gateway now supports > 30s?

2023-11-23 05:45 UTC, Hyodar commented on app/components/hooks/useDeposits.ts
> +async function queryDeposits(network: SupportedNetwork, timeline: Timeline, _: boolean = false): Promise<ApiDepositsResponse> {
Good! Maybe we can think about using cached entries from bigger ranges in the future? I don't think this needs to be in this PR though.

2023-11-23 05:45 UTC, Hyodar commented on app/components/hooks/useDepositsGrouping.ts
> +      // time = `${weekStart.format('YYYY-MM-DD')} to ${weekEnd.format('YYYY-MM-DD')}`;
Maybe should be removed?

2023-11-23 05:45 UTC, Hyodar commented on app/components/hooks/useWithdrawalsGrouping.ts
> +      // time = `${weekStart.format('YYYY-MM-DD')} to ${weekEnd.format('YYYY-MM-DD')}`;
Should probably also be removed

2023-11-23 05:45 UTC, Hyodar commented on app/utils/types.ts
> +export const timeline = ["1w", "1m", "1y", "full"] as const;
I think `supportedTimelines` or `timelines` would be a better name. I see functions that receive `timeline` that would quite easily clash with this, so it gets confusing.

2023-11-23 05:45 UTC, Hyodar commented on next.config.js
> +    // reactStrictMode: true,
Should probably be removed

2023-11-23 05:45 UTC, Hyodar commented on next.config.js
> +            config.externals.push({ bufferutil: "bufferutil", "utf-8-validate": "utf-8-validate", "supports-color": "supports-color" });
Can you explain this?

2023-11-23 05:45 UTC, Hyodar commented on package-lock.json
Ref. comment about `yarn`

2023-11-23 05:45 UTC, Hyodar commented on package.json
> +    "utf-8-validate": "^5.0.10"
This is probably related to the webpack changes. What is the idea?

2023-11-23 08:47 UTC, tdenisenko commented on api/package-lock.json
Agreed, will remove package-lock.json

2023-11-23 08:48 UTC, tdenisenko commented on api/serverless.yml
> +    timeout: 40
This was required while testing since I got too many timeout errors. It seems like queries got faster now, will switch back to 30s

2023-11-23 08:49 UTC, tdenisenko commented on app/components/hooks/useDeposits.ts
> +async function queryDeposits(network: SupportedNetwork, timeline: Timeline, _: boolean = false): Promise<ApiDepositsResponse> {
This was the main requirement for this branch, we want to be able to query different timelines

2023-11-23 08:49 UTC, tdenisenko commented on app/components/hooks/useDepositsGrouping.ts
> +      // time = `${weekStart.format('YYYY-MM-DD')} to ${weekEnd.format('YYYY-MM-DD')}`;
Will remove

2023-11-23 08:50 UTC, tdenisenko commented on app/components/hooks/useWithdrawalsGrouping.ts
> +      // time = `${weekStart.format('YYYY-MM-DD')} to ${weekEnd.format('YYYY-MM-DD')}`;
Will remove

2023-11-23 08:51 UTC, tdenisenko commented on app/utils/types.ts
> +export const timeline = ["1w", "1m", "1y", "full"] as const;
That makes sense

2023-11-23 08:51 UTC, tdenisenko commented on next.config.js
> +    // reactStrictMode: true,
Will remove

2023-11-23 08:59 UTC, tdenisenko commented on next.config.js
> +            config.externals.push({ bufferutil: "bufferutil", "utf-8-validate": "utf-8-validate", "supports-color": "supports-color" });
This fixed an error message thrown out regarding the bufferutil but I can probably revert this completely to its initial state

2023-11-23 08:59 UTC, tdenisenko commented on package-lock.json
Will remove

2023-11-23 09:00 UTC, tdenisenko commented on package.json
> +    "utf-8-validate": "^5.0.10"
Same explanation regarding `bufferutil` I will try to revert this

2023-11-23 09:12 UTC, tdenisenko commented
Requested changes made, please review

2023-11-24 20:24 UTC, Hyodar approved these changes
Added caching based on bigger time ranges, did some small changes and merged `dev` into here. Feel free to double-check and then merge into `dev`.

Do note the RPC URL env keys renaming on your `.env`.

2023-11-25 08:40 UTC, merged