add swell lrt
NethermindEth/restaking-dashboard pull request #86
Opened 2024-05-10 08:44 UTC by Zishan-7

- Added swell to LRT chart.

2024-05-10 14:25 UTC, rubo requested changes

2024-05-10 14:25 UTC, rubo commented on src/lrt/LRTDistribution.jsx
> +                      className="inline-block w-3 h-3 rounded-full"
The changes to this line seem unnecessary. Please revert. Below is alright.

2024-05-10 16:54 UTC, Zishan-7 commented on src/lrt/LRTDistribution.jsx
> +                      className="inline-block w-3 h-3 rounded-full"
Done 👍

2024-05-10 17:17 UTC, rubo commented on src/lrt/LRTDistribution.jsx
> +                      className="inline-block w-3 h-3 rounded-full"
I mean all the changes up to this line :)

2024-05-10 17:47 UTC, Zishan-7 commented on src/lrt/LRTDistribution.jsx
> +                      className="inline-block w-3 h-3 rounded-full"
Ah, sorry for the confusion, I have fixed it now.

2024-05-14 20:09 UTC, rubo approved these changes

2024-05-14 20:10 UTC, merged