feat: change AVS list content based on selected AVS
NethermindEth/restaking-dashboard pull request #87
Opened 2024-05-14 11:28 UTC by kushagrasarathe

2024-05-14 20:17 UTC, rubo reviewed
Please add a hover color (either `default` or `content1`) change to make it more interactive.

2024-05-15 05:34 UTC, kushagrasarathe commented
> default
@rubo  should also add a active color to show current selected AVS?

2024-05-15 09:03 UTC, rubo commented
Yes, please.

2024-05-20 15:04 UTC, rubo requested changes

2024-05-20 15:04 UTC, rubo commented on src/avs/AVSList.jsx
> +  const [selectedAVS, setSelectedAVS] = useState(null);
For the state updates, see the line above. We use mutative. As this view grows, we don't wanna have too many `useState.` If you need help with it, just let me know.

2024-05-21 18:51 UTC, rubo approved these changes

2024-05-29 08:39 UTC, merged