feature: avs details page ui with mock data
NethermindEth/restaking-dashboard pull request #93
Opened 2024-06-11 10:39 UTC by kushagrasarathe

2024-06-12 20:23 UTC, rubo commented on .env
This file is redundant. There is `.env.development` instead. Doesn't it work for you?

2024-06-14 09:18 UTC, vincenthongzy commented on src/avs/LSTDistributionGraph.jsx
Let's call this `LSTTreemap` instead

2024-06-14 09:18 UTC, vincenthongzy commented on src/avs/LSTDistributionGraph.jsx
> +  });
should wrap `hierarchy` and `scaleLinear` in a useMemo to prevent unnecessary recalculations

2024-06-14 09:18 UTC, vincenthongzy commented on src/avs/LSTDistributionGraph.jsx
> +  });
I'll have a PR up soon with an example using actual data, it is a little bit more involved than this because the backend doesn't return data in the shape that d3 expects

2024-06-16 15:00 UTC, kushagrasarathe commented on .env
Missed that, will remove it.

2024-06-17 09:26 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +
Currently broken due to new backend changes. Please convert the addresses to lowercase. You can assume every address from backend will be in lowercase.

2024-06-17 09:26 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +  },
Some of the names aren't correct, but I assume it was placed there for your demo. Please update them later. `lsETH` is Liquid Staked Eth

2024-06-17 12:43 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
> +
I've changed the addresses to lower case but won't push it in the next commits until we have that fixed from backend, it's breaking in the frontend if I use lower case values rn.

2024-06-17 12:48 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +
it's already on main branch. you need to reindex

2024-06-21 09:07 UTC, vincenthongzy requested changes

2024-06-21 09:21 UTC, vincenthongzy commented on src/shared/Pagination.jsx
> +  onPageClick
usually these are prefixed with `handle*` instead of `on`

2024-06-21 09:22 UTC, vincenthongzy commented on src/shared/Pagination.jsx
> +  onPageClick
let's keep them consistent throughout the codebase

2024-06-21 10:10 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +      )}
you don't have to calculate the top/left values. Just `useTooltip` from visx for that

2024-06-21 10:15 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +      )}
and you can access data using `tooltipData` from the hook

2024-06-23 13:00 UTC, kushagrasarathe commented on src/avs/Operators.jsx
> +    [];
yes, this was done to sort latest operators on frontend for now, we will change it to backend based sorting once we have it

2024-06-23 13:04 UTC, kushagrasarathe commented on src/shared/Layout.jsx
> +    <div className="bg-background min-h-screen flex flex-col text-foreground relative">
this was a change from another pr, to make sidebar stick, removing it from here as merging #92 will fix it

2024-06-23 17:06 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +      )}
I tried that approach at first but apparently, it did not work with `@visx/hierarchy` components.

2024-06-23 17:24 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +      )}
strange, i got it to work with mine

2024-06-24 13:44 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +      )}
curios, what was the original issue, did you manage to figure it out!

2024-06-24 17:34 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +      )}
could not figure out the exact reason but I think it was cause I was not using the `useTooltipInPortal` hook

2024-06-26 09:56 UTC, vincenthongzy requested changes

2024-06-26 09:56 UTC, vincenthongzy commented on src/avs/Operators.jsx
> +          handlePageClick={onPageClick}
```
handleNext={handleNext}
```

2024-06-26 09:56 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +        }}
this is not necessary, you don't have to store the mouseX and mouseY manually. It is accessible straight from the event

```
  const handleAreaPointerMove = useCallback(
    (event, stack) => {
      const point = localPoint(event.target.ownerSVGElement, event);

      showTooltip({
        tooltipData: { key: stack.key, data: stack[i].data, x },
        tooltipLeft: point.x,
        tooltipTop: point.y
      });
    },
    [showTooltip, scaleDate]
  );
```

2024-06-26 09:58 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +                    )}
did you forget to change this? it should be `onPointerEnter` , `onPointerMove` and `onPointerLeave`. The comment was mark as resolved but it hasn't been updated yet

2024-06-26 10:13 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +        }}
the reason I'm storing it in state is cuz I'm using the position to set tooltip position, and it's working smooth.
```
{tooltipOpen && tooltipData && (
        <TooltipInPortal
          key={Math.random()}
          top={state.mouseY}
          left={state.mouseX}
          className="backdrop-blur bg-white/75 dark:bg-black/75 p-2 rounded min-w-40 shadow-md text-foreground"
        >
          <div className="text-sm">
            {tooltipData.name}{' '}
            <span className="text-xs">{`(${tooltipData.token})`}</span>
          </div>
          <div className="text-base">
            TVL: {assetFormatter.format(tooltipData.tvl)}
          </div>
        </TooltipInPortal>
```

2024-06-26 10:15 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +        }}
you can get the positioning values from tooltipLeft and tooltipRight from `useTooltip` no?

2024-06-26 10:19 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +                    )}
Actually I did changed these, but then did not commit as the tooltip was already following cursor position.

2024-06-26 10:21 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +                    )}
ok sounds fair. please reply to the comments if you decided not to apply the suggestions so we can avoid overhead like this

2024-06-26 10:22 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +                    )}
@vincenthongzy this is how it looks with current version.

https://github.com/NethermindEth/restaking-dashboard/assets/76868364/e78816df-eff0-46f6-953d-29b4d67fbf94

2024-06-26 10:23 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +        }}
alright, I'll keep this in mind for next times :)

2024-06-26 10:30 UTC, kushagrasarathe commented on src/avs/LSTTreeMap.jsx
> +        }}
ideally yes, I was having some issues with the proper positioning of the tooltip in the last version of code when using the positions from hook, lemme try updating it in the current version and remove the mouseX and mouseY values altogether from the code

2024-06-26 10:32 UTC, vincenthongzy commented on src/avs/LSTTreeMap.jsx
> +        }}
yeah that's fair, if it takes too long to get it to work I am ok with this approach!

2024-06-26 16:50 UTC, rubo requested changes
The mock data should not be merged, we need to clean them up.

![misaligned](https://github.com/NethermindEth/restaking-dashboard/assets/337518/b9ad34ac-06ae-43c0-830d-8c33ed4803d2)

Not sure whether this misalignment should be addressed in this PR. Maybe separately.

2024-06-26 16:50 UTC, rubo commented on src/@services/AVSService.js
> +  async getAvsDetails(address) {
It should be `getAVSDetails`. We use the most popular naming conventions for JavaScript for consistency, although sometimes they get ugly.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +  const handleTimelineChange = tab => {
These functions should be wrapped in `useCallback`.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +  const convertToEther = bigIntValue => Number(bigIntValue / BigInt(1e18));
Should be wrapped in `useMemo`.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +              https://docs.eigenlayer.xyz/eigenda/overview/
Looks like a remnant.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +                    TVL overtime
Should be "over time" not "overtime".

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +                    </div>
Hardcoded things need to be removed.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSList.jsx
> +              style={{ background: '#191C2C' }}
Colors should not be hardcoded. This particular one is the `default` in `tailwind.config.js` colors.

2024-06-26 16:50 UTC, rubo commented on src/avs/AVSDetails.jsx
> +  const {
I'd prefer not destructuring the state, so it's easier to spot state items and distinguish them from other variables, as in that case, they are prefixed with `state.`.

2024-06-26 17:03 UTC, kushagrasarathe commented on src/avs/AVSList.jsx
> +              style={{ background: '#191C2C' }}
for some reason using the tailwind variable for color wasn't working when using inside classname in skeleton component. I'll try finding the reason and update it.

2024-06-27 12:52 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
> +                    </div>
same for this one, fixing in #98

2024-06-27 13:02 UTC, kushagrasarathe commented on src/avs/AVSList.jsx
> +              style={{ background: '#191C2C' }}
found the reason, it was cuz the theme is set to dark, so directly changing the color wasn't adding any effect, fixed it

2024-06-27 13:14 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
have renamed a few in other branches, can rename left one's after this pr is merged, idea was to keep avs related components inside `/avs` directory so that they can be easily distinguished

2024-06-27 14:09 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +  const handleTimelineChange = tab => {
@kushagrasarathe think you need to add in `useCallback` and `useMemo` in quite a few places around the various different files, instead of just adding it in for handleTimelineChange.

2024-06-27 14:35 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
> +  const handleTimelineChange = tab => {
@vincenthongzy  I've added on this file currently, and on other pr's have added too, I'd suggest we can update it once all these PRs are merged cuz it's kind of getting hard to track for each PR, wdyt?

2024-06-28 06:36 UTC, vincenthongzy commented on src/avs/AVSList.jsx
> +          state.avs?.map((avs, i) => (
bad news here, we have a AVS in the DB that looks like this without any metadata field.:

```
[
  {
    _id: ObjectId('667293069b56b5d843c6280d'),
    address: '0xb6827e919b55b45290cf54f006ee4a231e06f088'
  }
]
```

Page crashes when trying to render the list

2024-06-28 16:56 UTC, kushagrasarathe commented on src/avs/AVSList.jsx
> +          state.avs?.map((avs, i) => (
@vincenthongzy as discussed this can be addressed in a different PR

2024-07-01 14:51 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +    }
```suggestion
    if (
      avsAddress === '0x870679e138bcdf293b7ff14dd44b70fc97e12fc0' ||
      avsAddress === '0x1de75eaab2df55d467494a172652579e6fa4540e'
    ) {
      const strategy = strategiesMap[eigenEntry.proxy];
      return strategy ? BigInt(strategy.tokens) : BigInt(0);
    }
```

2024-07-01 14:51 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +    }
There's another AVS that has EIGEN enabled, putting this here first as I get confirmation from Clem.

2024-07-01 14:56 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +    }
Considering to also return a flag to frontend whether to include eigen or not

2024-07-02 12:16 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +    }
@kushagrasarathe can remove the filter on the frontend now, backend will return the relevant strategies

2024-07-02 18:58 UTC, kushagrasarathe commented on src/avs/AVSList.jsx
> +          state.avs?.map((avs, i) => (
this was fixed and merged in #102

2024-07-03 15:47 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
> +    }
@vincenthongzy  removed the filter

2024-07-04 07:14 UTC, vincenthongzy approved these changes

2024-07-04 07:17 UTC, merged