feature: add operators over time graph
NethermindEth/restaking-dashboard pull request #99
Opened 2024-06-27 12:39 UTC by kushagrasarathe

- adds operators over time graph and api integration 

<img width="1219" alt="Screenshot 2024-06-27 at 6 09 23 PM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/95a82804-b12f-40a6-86e3-765965a8a646">

2024-06-27 15:39 UTC, vincenthongzy commented
Is this graph showing the daily number of registered operators:
```
day 1: 1 new operator
day 2: 2 new operator
day 3: 3 new operator (does not show deregistration)
```
 or is this a graph showing the accumulation of operators over time?
```
day 1: 1 total
day 2 : 3 total
day 3: 5 total ( 1 de-registered from day2)
```

2024-06-27 15:39 UTC, vincenthongzy commented on src/avs/AVSDetails.jsx
> +            <OperatorsOverTime avsAddress={avsAddress} />
Is this graph showing the daily number of registered operators:
```
day 1: 1 new operator
day 2: 2 new operator
day 3: 3 new operator (does not show deregistration)
```
 or is this a graph showing the accumulation of operators over time?
```
day 1: 1 total
day 2 : 3 total
day 3: 5 total ( 1 de-registered from day2)
```

2024-06-28 03:45 UTC, kushagrasarathe commented on src/avs/AVSDetails.jsx
> +            <OperatorsOverTime avsAddress={avsAddress} />
@vincenthongzy  I'm not formatting the data on frontend, it's being represented the way it's received from backend. So I believe it's the later one (accumulation of operators over time).

Did I get your question right though? 👀

2024-06-28 04:08 UTC, vincenthongzy reviewed
The design doesn't seem to show verbose dates with the month, just the day. Is this change communicated with Carlos?

<img width="883" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/f46df6ed-f31e-4a80-950d-dfafb5d7724c">

2024-06-28 04:08 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +
Hm, how can all the values be the same? When the AVS is new and we have less than a few days worth of data?  

If so, could you update the comment and leave this context in ?

2024-06-28 04:10 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +          Operators over time
as discussed, we need to clarify with product what this graph is trying to represent here. Daily registrations over time or total operator count over time. Please update the title and leave a comment here when that's sorted out @kushagrasarathe

2024-06-28 04:18 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +    if (!graphData) return null;
hm when would this be null?

2024-06-28 16:58 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +    if (!graphData) return null;
if the data is not fetched from the api, the default value is null, so this check was added to prevent breaking the page

2024-06-28 16:59 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +          Operators over time
this needs to be `total operator count over time`, I'm working on fixing this 🫡

2024-06-28 17:01 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +      if (!sortedData || !xScale || !yScale) return;
@vincenthongzy we can do that, but the reason I chose x and y scales as names was to easily distinguish them based on the axis they are for.

2024-06-28 17:04 UTC, kushagrasarathe commented
> The design doesn't seem to show verbose dates with the month, just the day. Is this change communicated with Carlos?
> 
> <img alt="image" width="883" src="https://private-user-images.githubusercontent.com/107991825/344024955-f46df6ed-f31e-4a80-950d-dfafb5d7724c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTQxNDcsIm5iZiI6MTcxOTU5Mzg0NywicGF0aCI6Ii8xMDc5OTE4MjUvMzQ0MDI0OTU1LWY0NmRmNmVkLWYzMWUtNGE4MC05NTBkLWRmYWZiNWQ3NzI0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxNjU3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDc3OTQxODZjMDAyMmU2YWFhM2NmNWU3ZjE1NWE2MTMzZjBhZTA1YjJkMzZjMDIwYjgzMjI0ZDE4NTY2NTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o9AWIl0d2Rhz6c-YnKXV-FpKMZCSc5Viapk_3cmktPQ">

@vincenthongzy I improvised here, cuz user can have a better context if we show the verbose dates, instead of just day, otherwise things can be a little confusing from a users pov if I don't even know what the metrics is being represented based on, thoughts?

2024-06-28 17:05 UTC, kushagrasarathe commented
oops closed the pr by mistake!

2024-06-28 17:10 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +  };
I think there's no need to wrap it in a `useCallback` since it doesn't depend on any state/prop or have a side-effect, its more of a utility function.

2024-06-28 17:10 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +  };
`sortTimelineData` would be a better name?

2024-06-29 09:00 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +  };
> I think there's no need to wrap it in a `useCallback` since it doesn't depend on any state/prop or have a side-effect, its more of a utility function.

my bad, the function depends on timeline tab state, have wrapped it inside a `useCallback`

2024-06-29 09:15 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +
@vincenthongzy  I added this check to create a artificial range for y-axis cuz there's a case when the operators count is constant throughout different dates, which makes the y-axis render only single tick value, which looks kind of weird, so for that case I'm creating a range. See below screenshot of how it looks without this range

<img width="1167" alt="Screenshot 2024-06-29 at 2 42 24 PM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/0a7b42b9-7af3-448c-8d43-487dd7929bbb">

2024-06-29 09:17 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +          Operators over time
update: I've updated the backend pr to use `avs_snapshots` collection, lemme know if it needs any changes and if the approach is correct. Thanks

2024-07-01 09:34 UTC, vincenthongzy approved these changes

2024-07-01 09:34 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +              left={tooltipLeft - 250}
why the fixed pixel values here? :o

2024-07-01 09:40 UTC, vincenthongzy requested changes

2024-07-01 09:40 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
<img width="1373" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/6e7493f8-9ee1-4eb0-9beb-d6db5b36a5be">

did you rename the file? seems like its broken for me locally

2024-07-01 09:41 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +              left={tooltipLeft - 250}
<img width="1169" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/90ecc436-abc0-4a08-bdde-294a4552b29e">

seems like its causing the tooltip to be out of place

2024-07-01 09:44 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +              left={tooltipLeft - 250}
![image](https://github.com/NethermindEth/restaking-dashboard/assets/107991825/94b59ff0-3caf-454b-a1ae-17cc786abb27)

same problem with @Zishan-7 PR, the tooltips are not showing correctly

2024-07-01 09:47 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +              left={tooltipLeft - 250}
another example of it behaving weirdly 

https://github.com/NethermindEth/restaking-dashboard/pull/100#discussion_r1660746982

2024-07-01 09:49 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
<img width="942" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/7077e872-311c-4a23-91df-da5aed2f3ff7">

dates are broken on smaller screens + the y axis should be whole numbers and not have `.0`

2024-07-02 11:50 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
@vincenthongzy  working on replacing all the graphs to follow similar structure and fixing tooltip with Zishan's approach. other than that everything else looks good on this PR to you?

2024-07-02 12:59 UTC, kushagrasarathe commented on src/avs/OperatorsOverTime.jsx
> +              left={tooltipLeft - 250}
have pushed a fix, tooltip is working fine now

2024-07-02 13:49 UTC, vincenthongzy requested changes

2024-07-02 13:49 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +  }, [avsService, dispatch, avsAddress]);
We should move the function definition in here. Otherwise this dependency array is wrong, it has to be `[fetchOperatorOvertime]`, and you need to wrap `fetchOperatorOvertime` in `useCallback`. Better move it here as a IIFE

2024-07-02 13:49 UTC, vincenthongzy commented on src/avs/OperatorsOverTimeChart.jsx
> +    [localPoint, dateScale, margin, showTooltip, getOperatorsByDate]
`[localPoint, dateScale, margin, showTooltip, getOperatorsByDate]`

getOperatorsByDate  is not wrapped in `useCallback`, so its doing nothing in the dependency array here

2024-07-02 13:49 UTC, vincenthongzy commented on src/avs/OperatorsOverTime.jsx
> +        </ParentSize>
Hey can you double check if its responsive? I tried it on my end but it just gives a horizontal overflow instead. There is no resizing of the charts happening

<img width="1065" alt="image" src="https://github.com/NethermindEth/restaking-dashboard/assets/107991825/d8205cef-ba7c-4e61-86ac-b2adb187237b">

2024-07-02 13:49 UTC, vincenthongzy commented on src/avs/Operators.jsx
> +          {filteredOperators.length ? (
here is a issue here, if you go to the next page, you will see that the operator's logo image does not change immediately. Either we fix this or add a skeleton.

2024-07-02 15:00 UTC, kushagrasarathe commented on src/avs/Operators.jsx
> +          {filteredOperators.length ? (
@vincenthongzy  does this look good?

https://github.com/NethermindEth/restaking-dashboard/assets/76868364/cff8eff5-fed7-4ae7-96e7-07333ce0b597

2024-07-02 15:02 UTC, vincenthongzy commented on src/avs/Operators.jsx
> +          {filteredOperators.length ? (
nice!

2024-07-02 15:22 UTC, vincenthongzy commented on src/avs/OperatorsOverTimeChart.jsx
> -    [localPoint, dateScale, margin, showTooltip, getOperatorsByDate]
you need to wrap `getOperatorsByDate` in a useCallback. Not remove it, or the useCallback dependency array is wrong. If its not used anywhere, can possibly just move it in this chunk

2024-07-02 15:33 UTC, kushagrasarathe commented on src/avs/OperatorsOverTimeChart.jsx
> -    [localPoint, dateScale, margin, showTooltip, getOperatorsByDate]
moved it inside the function, was only being used in one place

2024-07-02 15:34 UTC, vincenthongzy approved these changes

2024-07-02 16:09 UTC, vincenthongzy approved these changes
good stuff

2024-07-02 16:09 UTC, vincenthongzy commented on src/avs/OperatorsOvertimeChart.jsx
> +                  cx={tooltipLeft - margin.left}
since you minus off margin.left here, maybe you don't need to add it in in line 88?

2024-07-02 18:53 UTC, kushagrasarathe commented on src/avs/OperatorsOvertimeChart.jsx
> +                  cx={tooltipLeft - margin.left}
@vincenthongzy  actually it is important to add, otherwise I'm not able to move the cursor to last data-point and see it's tooltip, see below screenshots, 1st one is with addition of `margin.left` and second one is wh

<img width="200" height="250" alt="Screenshot 2024-07-03 at 12 20 45 AM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/baaaedec-76a4-4534-9c54-59bb4d4bc997">

<img width="200" height="250" alt="Screenshot 2024-07-03 at 12 21 13 AM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/b0b92256-16f8-45e9-9a4b-500272893212">

2024-07-03 02:54 UTC, vincenthongzy commented on src/avs/OperatorsOvertimeChart.jsx
> +                  cx={tooltipLeft - margin.left}
oh ok my bad, this is for the circle svg, not the tooltip. All's good, thanks!

2024-07-03 11:10 UTC, merged